Repository VagrantAI-c/ng-carousel-cdk, pull requests merged in 2019-09, with the labels that each got.

#14 Organize library dependencies
  projects/ng-carousel/package.json
Labels: enhancement

#15 Release
  projects/ng-carousel/package.json
  projects/ng-carousel/src/lib/carousel-config.ts
Labels: release

#16 feat: specify repository
  projects/ng-carousel/package.json
Labels: enhancement

#17 chore: add commitizen command
  package.json
Labels: enhancement

#18 fix: specify whitelisted dependency
  projects/ng-carousel/ng-package.json
  projects/ng-carousel/package.json
Labels: bug

#19 Release
  projects/ng-carousel/ng-package.json
  projects/ng-carousel/package.json
Labels: release

#20 fix: remove redundant animations module
  projects/ng-carousel/src/lib/carousel.module.ts
Labels: bug

#21 Release
  projects/ng-carousel/src/lib/carousel.module.ts
Labels: release

#22 fix: allow empty slides initializer
  package-lock.json
  package.json
  projects/ng-carousel/src/lib/private/service/carousel.service.ts
Labels: bug

#23 Release
  package-lock.json
  package.json
  projects/ng-carousel/src/lib/private/service/carousel.service.ts
Labels: release

#24 fix: fix incorrect carousel height
  projects/ng-carousel/src/lib/carousel.component.scss
Labels: bug

#25 Release
  projects/ng-carousel/src/lib/carousel.component.scss
Labels: release

#26 feat: implement ghost click prevention
  README.md
  projects/ng-carousel/src/lib/carousel.component.scss
  projects/ng-carousel/src/lib/carousel.component.ts
  projects/ng-carousel/src/lib/carousel.module.ts
  projects/ng-carousel/src/lib/prevent-ghost-click.directive.ts
  projects/ng-carousel/src/lib/private/service/hammer.service.ts
  projects/ng-carousel/src/lib/private/views/carousel-engine.component.ts
  projects/ng-carousel/src/public-api.ts
  src/app/app.component.html
Labels: enhancement

#28 Release
  projects/ng-carousel/src/lib/carousel.component.ts
  projects/ng-carousel/src/lib/prevent-ghost-click.directive.ts
  projects/ng-carousel/src/lib/private/service/hammer-provider.service.ts
  projects/ng-carousel/src/lib/private/views/carousel-engine.component.ts
Labels: release

#29 fix: stop ghost click propagation
  projects/ng-carousel/src/lib/prevent-ghost-click.directive.ts
Labels: enhancement

#30 Release
  projects/ng-carousel/src/lib/prevent-ghost-click.directive.ts
Labels: release

#31 fix: hidden overflow on carousel engine
  projects/ng-carousel/src/lib/carousel.component.scss
Labels: bug

#32 fix: fix server side code
  projects/ng-carousel/src/lib/prevent-ghost-click.directive.ts
  projects/ng-carousel/src/lib/private/views/carousel-engine.component.ts
Labels: bug

#33 fix: don't listen browser events on server
  projects/ng-carousel/src/lib/private/views/carousel-engine.component.ts
Labels: bug

#34 Release
  projects/ng-carousel/src/lib/private/views/carousel-engine.component.ts
Labels: release

#35 fix: infinite loop on server rendering
  angular.json
  package-lock.json
  package.json
  projects/ng-carousel/package.json
  projects/ng-carousel/src/lib/private/service/carousel.service.ts
  server.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/app.server.module.ts
  src/assets/robots.txt
  src/main.server.ts
  src/main.ts
  tsconfig.json
  tsconfig.server.json
  webpack.server.config.js
Labels: bug

#37 chore: missing library build step
  .travis.yml
Labels: bug

#36 Release
  .travis.yml
  angular.json
  package-lock.json
  package.json
  projects/ng-carousel/package.json
  projects/ng-carousel/src/lib/private/service/carousel.service.ts
  server.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/app.server.module.ts
  src/assets/robots.txt
  src/main.server.ts
  src/main.ts
  tsconfig.json
  tsconfig.server.json
  webpack.server.config.js
Labels: release

#38 fix: missing browser checks
  package-lock.json
  package.json
  projects/ng-carousel/src/lib/private/service/carousel.service.ts
Labels: release

#39 ci: change gh publish target folder
  package.json
Labels: bug, release

#40 chore: fix gh publish folder
  .travis.yml
Labels: bug, release

#42 Release
  projects/ng-carousel/src/lib/private/views/carousel-engine.component.ts
Labels: release

#43 Release
  projects/ng-carousel/src/lib/prevent-ghost-click.directive.ts
  projects/ng-carousel/src/lib/private/views/carousel-engine.component.ts
  src/app/app.component.ts
Labels: release

#44 Release
  server.ts
Labels: release
