Repository VagrantAI-c/ng-carousel-cdk, pull requests merged in 2020-02, with the labels that each got.

#49 build: fix chrome addon
  .travis.yml
Labels: bug

#48 feat: export item index to slide template
  README.md
  projects/ng-carousel/src/lib/private/models/carousel-slide-context.ts
  projects/ng-carousel/src/lib/private/views/carousel-engine.component.ts
Labels: enhancement

#50 chore: bump dependencies
  package-lock.json
  package.json
Labels: dependencies

#51 Release
  .travis.yml
  README.md
  package-lock.json
  package.json
  projects/ng-carousel/src/lib/private/models/carousel-slide-context.ts
  projects/ng-carousel/src/lib/private/views/carousel-engine.component.ts
Labels: release

#52 fix: postpone setIndex when no slides available
  README.md
  projects/ng-carousel/src/lib/private/service/carousel.service.ts
  projects/ng-carousel/src/lib/private/service/helpers/find-slide-index.spec.ts
  projects/ng-carousel/src/lib/private/service/helpers/find-slide-index.ts
Labels: bug

#53 Feature/version bump
  angular.json
  package-lock.json
  package.json
  projects/ng-carousel/src/lib/carousel.component.ts
  projects/ng-carousel/src/lib/private/views/carousel-engine.component.ts
  projects/ng-carousel/tsconfig.lib.json
  projects/ng-carousel/tsconfig.lib.prod.json
  server.ts
  src/app/app.module.ts
  src/app/app.server.module.ts
  src/main.server.ts
  src/main.ts
  tsconfig.app.json
  tsconfig.server.json
  webpack.server.config.js
Labels: dependencies
